# Generated by Django 5.1.3 on 2026-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aicharacter_aiconversation_aimessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='temperature',
            field=models.FloatField(default=0.7, verbose_name='默认 Temperature'),
        ),
    ]
