# Generated by Django 5.1.3 on 2026-06-17 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aiproviderconfig_temperature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='版本名称')),
                ('messages_json', models.JSONField(verbose_name='消息数据')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='blog.aicharacter')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='blog.aiconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天快照',
                'verbose_name_plural': '聊天快照',
                'ordering': ['-created_at'],
            },
        ),
    ]
