# Generated by Django 5.1.3 on 2026-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aiconversationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='quote',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
