# Generated by Django 5.1.3 on 2026-06-17 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aimessage_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversationsnapshot',
            options={'ordering': ['slot_index'], 'verbose_name': '聊天快照', 'verbose_name_plural': '聊天快照'},
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='自定义名称'),
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='slot_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='存档槽位'),
        ),
        migrations.AlterUniqueTogether(
            name='aiconversationsnapshot',
            unique_together={('user', 'character', 'slot_index')},
        ),
    ]
