# Generated by Django 5.1.3 on 2026-06-17 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_aiconversationsnapshot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='character_avatar_url',
            field=models.TextField(blank=True, default='', verbose_name='人物快照头像URL'),
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='character_model_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='人物快照模型名称'),
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='人物快照名称'),
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='保存时间'),
        ),
        migrations.AlterField(
            model_name='aiconversationsnapshot',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='blog.aicharacter'),
        ),
        migrations.AlterField(
            model_name='aiconversationsnapshot',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='版本名称'),
        ),
    ]
