# Generated by Django 5.1.3 on 2026-06-17 06:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_aiconversationsnapshot_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiconversationsnapshot',
            unique_together={('user', 'character_name', 'slot_index')},
        ),
    ]
