# Generated by Django 5.1.3 on 2026-06-17 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_aiconversationsnapshot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
