# Generated by Django 5.1.3 on 2026-06-17 07:53

from django.conf import settings
from django.db import migrations, models


import random

def generate_ai_uid_for_migration(apps, schema_editor):
    AICharacter = apps.get_model('blog', 'AICharacter')
    AIConversationSnapshot = apps.get_model('blog', 'AIConversationSnapshot')
    
    # 1. Fix AICharacters
    for char in AICharacter.objects.all():
        if not char.ai_uid:
            while True:
                code = ''.join(random.choices('0123456789', k=8))
                if not AICharacter.objects.filter(user=char.user, ai_uid=code).exists():
                    char.ai_uid = code
                    char.save()
                    break
    
    # 2. Fix Snapshots
    for ss in AIConversationSnapshot.objects.all():
        if not ss.ai_uid:
            if ss.character:
                # If char exists, use its ai_uid
                ss.ai_uid = ss.character.ai_uid
                ss.save()
            else:
                # If char deleted, find by name or generate new
                # Find all snapshots with same character_name for this user
                same_group = AIConversationSnapshot.objects.filter(
                    user=ss.user, 
                    character_name=ss.character_name
                )
                
                # Check if any in group already has an ai_uid
                existing_uid = None
                for other in same_group:
                    if other.ai_uid:
                        existing_uid = other.ai_uid
                        break
                
                if not existing_uid:
                    # Generate one for the group
                    while True:
                        code = ''.join(random.choices('0123456789', k=8))
                        if not AICharacter.objects.filter(user=ss.user, ai_uid=code).exists() and \
                           not AIConversationSnapshot.objects.filter(user=ss.user, ai_uid=code).exists():
                            existing_uid = code
                            break
                
                ss.ai_uid = existing_uid
                ss.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_aimessage_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicharacter',
            name='ai_uid',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='角色码'),
        ),
        migrations.AddField(
            model_name='aiconversationsnapshot',
            name='ai_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='角色码'),
        ),
        migrations.RunPython(generate_ai_uid_for_migration),
        migrations.AlterUniqueTogether(
            name='aicharacter',
            unique_together={('user', 'ai_uid')},
        ),
        migrations.AlterUniqueTogether(
            name='aiconversationsnapshot',
            unique_together={('user', 'ai_uid', 'slot_index')},
        ),
    ]
