# Generated by Django 5.1.3 on 2026-06-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_aiconversationsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/users/', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公开主页'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=9, null=True, unique=True, verbose_name='公开ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_dating_profile',
            field=models.BooleanField(default=False, verbose_name='显示交友资料'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_location',
            field=models.BooleanField(default=False, verbose_name='显示所在地'),
        ),
    ]
