# Generated by Django 5.1.3 on 2026-06-19 02:19

from django.db import migrations
import random

def fill_public_ids(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('blog', 'UserProfile')
    
    # 1. Ensure all users have a Profile
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)
    
    markus_email = 'sglock220@gmail.com'
    markus_public_id = 'A00000001'
    
    # 2. Handle conflicts for A00000001
    existing_a00000001 = UserProfile.objects.filter(public_id=markus_public_id).first()
    if existing_a00000001:
        if existing_a00000001.user.email != markus_email:
            # Generate a new ID for the conflicting user
            while True:
                new_id = 'A' + ''.join(random.choices('0123456789', k=8))
                if not UserProfile.objects.filter(public_id=new_id).exists():
                    existing_a00000001.public_id = new_id
                    existing_a00000001.save()
                    break
    
    # 3. Set Markus's ID
    markus = User.objects.filter(email=markus_email).first()
    if markus:
        profile = UserProfile.objects.get(user=markus)
        profile.public_id = markus_public_id
        profile.save()
    
    # 4. Fill other empty public_ids
    for profile in UserProfile.objects.filter(public_id__isnull=True):
        while True:
            new_id = 'A' + ''.join(random.choices('0123456789', k=8))
            if not UserProfile.objects.filter(public_id=new_id).exists():
                profile.public_id = new_id
                profile.save()
                break
    
    for profile in UserProfile.objects.filter(public_id=''):
        while True:
            new_id = 'A' + ''.join(random.choices('0123456789', k=8))
            if not UserProfile.objects.filter(public_id=new_id).exists():
                profile.public_id = new_id
                profile.save()
                break

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userprofile_cover_image_userprofile_is_public_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_public_ids),
    ]
