# Generated by Django 5.1.3 on 2026-06-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_fill_user_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=9, unique=True, verbose_name='公开ID'),
        ),
    ]
