# Generated by Django 5.1.3 on 2026-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_userprofile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('private', '仅本人'), ('friends', '好友可见'), ('public', '公开')], default='private', max_length=20, verbose_name='可见性'),
        ),
    ]
