# Generated by Django 5.1.3 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_bookmarks_public',
            field=models.BooleanField(default=False, verbose_name='公开收藏'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_followers_public',
            field=models.BooleanField(default=True, verbose_name='公开粉丝列表'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_following_public',
            field=models.BooleanField(default=True, verbose_name='公开关注列表'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_notes_public',
            field=models.BooleanField(default=True, verbose_name='公开笔记'),
        ),
    ]
