# Generated by Django 5.1.3 on 2026-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_userprofile_show_bookmarks_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_original',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/users/original/', verbose_name='头像原图'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image_original',
            field=models.ImageField(blank=True, null=True, upload_to='covers/users/original/', verbose_name='封面图原图'),
        ),
    ]
