# Generated by Django 5.1.3 on 2026-07-14 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_userprofile_avatar_original_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_wallpaper',
            field=models.CharField(blank=True, max_length=255, verbose_name='当前使用的壁纸'),
        ),
        migrations.CreateModel(
            name='UserWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wallpapers/users/', verbose_name='壁纸图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户壁纸',
                'verbose_name_plural': '用户壁纸',
                'ordering': ['-created_at'],
            },
        ),
    ]
