# Generated by Django 5.1.3 on 2026-07-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_emailverificationcode_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_background_color',
            field=models.CharField(default='#f5f5f5', max_length=20, verbose_name='当前纯色背景'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_background_type',
            field=models.CharField(default='image', max_length=20, verbose_name='当前背景类型'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_wallpaper_kind',
            field=models.CharField(default='default', max_length=20, verbose_name='当前壁纸来源'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_wallpaper_mode',
            field=models.CharField(default='pc', max_length=20, verbose_name='当前壁纸模式'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_wallpaper_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_profiles', to='blog.userwallpaper', verbose_name='当前自定义壁纸'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallpaper_shortcuts',
            field=models.JSONField(blank=True, default=list, verbose_name='快捷壁纸槽'),
        ),
        migrations.AddField(
            model_name='userwallpaper',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/users/mobile/', verbose_name='手机壁纸'),
        ),
        migrations.AddField(
            model_name='userwallpaper',
            name='name',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='壁纸名称'),
        ),
        migrations.AddField(
            model_name='userwallpaper',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/users/original/', verbose_name='壁纸原图'),
        ),
        migrations.AddField(
            model_name='userwallpaper',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/users/pc/', verbose_name='PC壁纸'),
        ),
        migrations.AddField(
            model_name='userwallpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
