# Generated by Django 5.1.3 on 2026-07-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_userprofile_current_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicharacter',
            name='aliases',
            field=models.JSONField(blank=True, default=list, verbose_name='角色小名'),
        ),
        migrations.AddField(
            model_name='aicharacter',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='角色姓名'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='是否群聊'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_conversations', to='blog.aicharacter', verbose_name='群聊成员'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='sender_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='blog.aicharacter'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='角色昵称'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='blog.aicharacter'),
        ),
    ]
