# Generated by Django 6.0.5 on 2026-08-10 13:56

from django.db import migrations, models


def migrate_skill_sections(apps, schema_editor):
    Resume = apps.get_model('blog', 'Resume')
    old_sections = [
        ('tools_text', '工具/软件/技术栈'),
        ('computer_text', '计算机方向'),
        ('vehicle_text', '车辆工程方向'),
    ]

    for resume in Resume.objects.all():
        if resume.skill_sections:
            continue

        skill_sections = []
        for index, (field_name, title) in enumerate(old_sections):
            description = (getattr(resume, field_name, '') or '').strip()
            if not description:
                continue
            skill_sections.append({
                'id': f'migrated-{field_name}',
                'title': title,
                'description': description,
                'order': index,
            })

        if skill_sections:
            resume.skill_sections = skill_sections
            resume.save(update_fields=['skill_sections'])


def reverse_skill_sections(apps, schema_editor):
    Resume = apps.get_model('blog', 'Resume')
    field_by_title = {
        '工具/软件/技术栈': 'tools_text',
        '计算机方向': 'computer_text',
        '车辆工程方向': 'vehicle_text',
    }

    for resume in Resume.objects.all():
        for section in resume.skill_sections or []:
            field_name = field_by_title.get(section.get('title'))
            if field_name:
                setattr(resume, field_name, section.get('description', ''))
        resume.save(update_fields=['tools_text', 'computer_text', 'vehicle_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_skill_sections, reverse_skill_sections),
        migrations.RemoveField(
            model_name='resume',
            name='computer_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tools_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='vehicle_text',
        ),
    ]
