# Generated by Django 6.0.5 on 2026-08-10 14:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_resume_text_to_zh(apps, schema_editor):
    Resume = apps.get_model('blog', 'Resume')
    ResumeTranslation = apps.get_model('blog', 'ResumeTranslation')

    for resume in Resume.objects.all():
        ResumeTranslation.objects.update_or_create(
            resume=resume,
            language='zh',
            defaults={
                'full_name': resume.full_name or '',
                'city': resume.city or '',
                'educations': resume.educations or [],
                'skill_sections': resume.skill_sections or [],
                'projects': resume.projects or [],
                'languages': resume.languages or [],
                'competitions': resume.competitions or [],
                'extras': resume.extras or [],
            },
        )


def restore_zh_translation_to_resume(apps, schema_editor):
    Resume = apps.get_model('blog', 'Resume')
    ResumeTranslation = apps.get_model('blog', 'ResumeTranslation')

    for resume in Resume.objects.all():
        translation = ResumeTranslation.objects.filter(resume=resume, language='zh').first()
        if not translation:
            continue
        resume.full_name = translation.full_name
        resume.city = translation.city
        resume.educations = translation.educations
        resume.skill_sections = translation.skill_sections
        resume.projects = translation.projects
        resume.languages = translation.languages
        resume.competitions = translation.competitions
        resume.extras = translation.extras
        resume.save(update_fields=[
            'full_name', 'city', 'educations', 'skill_sections',
            'projects', 'languages', 'competitions', 'extras'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_resume_computer_text_remove_resume_tools_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh', 'Chinese'), ('de', 'German'), ('en', 'English')], max_length=2)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('educations', models.JSONField(blank=True, default=list)),
                ('skill_sections', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('competitions', models.JSONField(blank=True, default=list)),
                ('extras', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.resume')),
            ],
            options={
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('resume', 'language'), name='unique_resume_translation_language')],
            },
        ),
        migrations.RunPython(migrate_existing_resume_text_to_zh, restore_zh_translation_to_resume),
        migrations.RemoveField(
            model_name='resume',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='competitions',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_sections',
        ),
    ]
