# Generated by Django 6.0.5 on 2026-08-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_resume_city_remove_resume_competitions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh', 'Chinese'), ('de', 'German'), ('en', 'English')], max_length=2)),
                ('file', models.FileField(upload_to='resumes/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='blog.resume')),
            ],
            options={
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('resume', 'language'), name='unique_resume_pdf_language')],
            },
        ),
    ]
