# Generated by Codex on 2026-08-10

from django.db import migrations, models


RESUME_LANGS = ("zh", "de", "en")


def move_contact_to_translations(apps, schema_editor):
    Resume = apps.get_model("blog", "Resume")
    ResumeTranslation = apps.get_model("blog", "ResumeTranslation")

    for resume in Resume.objects.all().iterator():
        phone = getattr(resume, "phone", "") or ""
        email = getattr(resume, "email", "") or ""
        if not phone and not email:
            continue

        for language in RESUME_LANGS:
            translation, _ = ResumeTranslation.objects.get_or_create(
                resume=resume,
                language=language,
            )
            changed = []
            if phone and not translation.phone:
                translation.phone = phone
                changed.append("phone")
            if email and not translation.email:
                translation.email = email
                changed.append("email")
            if changed:
                translation.save(update_fields=changed + ["updated_at"])


def move_contact_to_resume(apps, schema_editor):
    Resume = apps.get_model("blog", "Resume")
    ResumeTranslation = apps.get_model("blog", "ResumeTranslation")

    for resume in Resume.objects.all().iterator():
        translation = (
            ResumeTranslation.objects.filter(resume=resume, language="zh").first()
            or ResumeTranslation.objects.filter(resume=resume).first()
        )
        if not translation:
            continue

        resume.phone = translation.phone or ""
        resume.email = translation.email or ""
        resume.save(update_fields=["phone", "email", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_resumepdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetranslation",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="resumetranslation",
            name="phone",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.RunPython(move_contact_to_translations, move_contact_to_resume),
        migrations.RemoveField(
            model_name="resume",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="phone",
        ),
    ]
